In [1]:
import pandas as pd
import qgrid

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix


# Read in the data from the CSV file
df = pd.read_csv(r'/Users/raghav-pc/PyProj/MSSEc/Chap2/datasets/payment.csv')

df.sample(10)

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
9874,206,1,5.040929,paypal,0.000694,0
8792,889,1,4.921349,creditcard,0.000000,0
8059,571,1,5.017904,creditcard,0.000694,0
14197,105,1,5.040929,paypal,104.331944,0
11200,1938,1,4.895263,creditcard,511.868750,0
15005,1007,1,4.524580,creditcard,0.000000,0
12926,740,1,4.921349,creditcard,0.000000,0
2950,2000,1,3.483951,creditcard,867.132639,0
29098,2000,1,4.745402,creditcard,588.138889,0
4451,2000,1,4.962055,creditcard,0.000694,0