In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix


# Read in the data from the CSV file
df = pd.read_csv(r'/Users/raghav-pc/PyProj/MSSEc/Chap2/datasets/payment.csv')

df.sample(30)

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
19520,2000,1,4.876771,creditcard,272.023611,0
18419,114,1,4.895263,creditcard,113.921528,0
12898,51,1,4.836982,creditcard,0.000000,0
22786,1313,1,4.921318,creditcard,0.000694,0
31183,909,1,4.461622,creditcard,0.462500,0
36976,140,1,4.965339,paypal,0.000000,0
6761,1587,1,4.921349,creditcard,0.000000,0
5444,1783,1,4.836982,creditcard,0.000000,0
5744,170,1,4.921318,creditcard,0.000000,0
12659,1610,1,4.836982,creditcard,76.791667,0
37263,29,1,5.034622,creditcard,0.000694,0
32446,115,1,4.921349,paypal,114.001389,0
15132,2000,1,4.921318,creditcard,0.000694,0
10746,1993,1,3.066058,paypal,47.137500,0
22966,320,1,5.040929,storecredit,319.377083,0
756,238,1,4.836982,creditcard,237.668750,0
32304,684,1,4.748314,paypal,349.727778,0
19679,2000,1,4.876771,creditcard,0.049306,0
30808,2000,1,4.895263,creditcard,0.000000,0
10314,2,1,4.836982,creditcard,0.028472,0
7356,106,1,5.034622,paypal,105.228472,0
10119,314,1,5.017904,creditcard,0.000000,0
32374,14,1,4.921349,creditcard,13.155556,0
28324,970,1,4.965339,storecredit,36.926389,0
28984,807,1,4.524580,creditcard,0.000000,0
25076,2000,1,4.962055,creditcard,315.878472,0
11713,111,1,4.965339,creditcard,110.843056,0
19672,27,1,4.962055,creditcard,0.004861,0
9585,64,1,4.921349,creditcard,0.000000,0
5211,720,1,4.461622,creditcard,0.000000,0